# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Arash Pourhabibi-Zarandi
tagline:             'A Software Engineer Who Loves His Job.'
#description:         There are only 10 types of people in the world. Those who undertand binary and those who don't, and those who count from zero.
description:
url:                 http://127.0.0.1:4000
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Arash Pourhabibi-Zarandi
  url:               http://arash.pourhabibi.info
  email:             arash.p.z@gmail.com
  twitter:           ArashPourhabibi
  facebook:          arash.p.zarandi
  googleplus:           ArashPourhabibiZarandi
  github:            neo-apz
  linkedin:          arashpourhabibizarandi

# Custom vars
version:             1.0.0

gems:
  - jemoji
  - jekyll-sitemap
