# Dependencies
markdown:            kramdown
highlighter:         rouge
kramdown:
  input: GFM

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Arash Pourhabibi-Zarandi
tagline:             'A Computer Engineer Who Loves His Job.'
description:
url:                 http://arash.pourhabibi.info/
baseurl:             /
paginate:            5
paginate_path: "/blog/page:num"

# About/contact
author:
  name:              Arash Pourhabibi-Zarandi
  url:               http://arash.pourhabibi.info
  email:             arash.pourhabibi@epfl.ch
  twitter:           ArashPourhabibi
  facebook:          arash.p.zarandi
  googleplus:           ArashPourhabibiZarandi
  github:            neo-apz
  linkedin:          arashpourhabibizarandi

# Custom vars
version:             1.0.0

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

collections:
  projects:
    output: true
